server:
  servlet:
    contextPath: /learn
  port: 8080
spring:
  gson:
    serialize-nulls : true
  application:
    name: learnsrv
  profiles:
    active:
      default
  cloud:
    config:
      enabled: false
  eureka:
    client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/





