server:
  port: 8888
  servlet:
    contextPath: /confsrv
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/config/learnsrv